#############################################################################
# Makefile for building: QR-Code
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  QR-Code.pro
# Template: app
# Command: /usr/sbin/x86_64-w64-mingw32-qmake-qt5 -o Makefile QR-Code.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

first: release
install: release-install
uninstall: release-uninstall
QMAKE         = /usr/sbin/x86_64-w64-mingw32-qmake-qt5
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/sbin/x86_64-w64-mingw32-qmake-qt5 -install qinstall
QINSTALL_PROGRAM = /usr/sbin/x86_64-w64-mingw32-qmake-qt5 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
IDC           = idc
IDL           = x86_64-w64-mingw32-widl
ZIP           = 
DEF_FILE      = 
RES_FILE      = QR-Code_resource_res.o
SED           = sed
MOVE          = mv -f
SUBTARGETS    =  \
		release \
		debug


release: FORCE
	$(MAKE) -f $(MAKEFILE).Release
release-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Release 
release-all: FORCE
	$(MAKE) -f $(MAKEFILE).Release all
release-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Release clean
release-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Release distclean
release-install: FORCE
	$(MAKE) -f $(MAKEFILE).Release install
release-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Release uninstall
debug: FORCE
	$(MAKE) -f $(MAKEFILE).Debug
debug-make_first: FORCE
	$(MAKE) -f $(MAKEFILE).Debug 
debug-all: FORCE
	$(MAKE) -f $(MAKEFILE).Debug all
debug-clean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug clean
debug-distclean: FORCE
	$(MAKE) -f $(MAKEFILE).Debug distclean
debug-install: FORCE
	$(MAKE) -f $(MAKEFILE).Debug install
debug-uninstall: FORCE
	$(MAKE) -f $(MAKEFILE).Debug uninstall

Makefile: QR-Code.pro /usr/x86_64-w64-mingw32/lib/qt/mkspecs/win32-g++/qmake.conf /usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/spec_pre.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/qdevice.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/device_config.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/sanitize.conf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/gcc-base.conf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/g++-base.conf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/angle.conf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/win32/windows_vulkan_sdk.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/windows-vulkan.conf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/g++-win32.conf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/windows-desktop.conf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/qconfig.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_core.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_core_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_dbus.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_designer.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_gui.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_help.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_help_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_location.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_location_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_network.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_network_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_opengl.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_positioning.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qml.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quick.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_script.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_script_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_scripttools.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_sensors.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_serialport.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_sql.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_svg.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_testlib.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_uitools.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_websockets.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_widgets.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_winextras.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_winextras_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_xml.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_zlib_private.pri \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/qt_functions.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/qt_config.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/win32-g++/qmake.conf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/exclusive_builds.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/toolchain.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/default_pre.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/win32/default_pre.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/resolve_config.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/exclusive_builds_post.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/default_post.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/precompile_header.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/warn_on.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/qt.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/resources_functions.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/resources.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/moc.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/win32/opengl.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/uic.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/qmake_use.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/file_copies.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/win32/windows.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/testcase_targets.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/exceptions.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/yacc.prf \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/lex.prf \
		QR-Code.pro \
		/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/build_pass.prf \
		translations.qrc
	$(QMAKE) -o Makefile QR-Code.pro
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/spec_pre.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/qdevice.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/device_config.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/sanitize.conf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/gcc-base.conf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/g++-base.conf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/angle.conf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/win32/windows_vulkan_sdk.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/windows-vulkan.conf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/g++-win32.conf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/common/windows-desktop.conf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/qconfig.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_concurrent.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_core.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_core_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_dbus.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_designer.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_designer_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_gui.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_gui_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_help.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_help_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_location.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_location_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_multimedia.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_network.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_network_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_opengl.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_positioning.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_printsupport.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qml.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qml_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmltest.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quick.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quick_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_script.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_script_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_scripttools.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_scripttools_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_sensors.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_serialport.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_serialport_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_sql.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_sql_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_svg.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_svg_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_testlib.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_uitools.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_websockets.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_widgets.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_windowsuiautomation_support_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_winextras.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_winextras_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_xml.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_xml_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/modules/qt_lib_zlib_private.pri:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/qt_functions.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/qt_config.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/win32-g++/qmake.conf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/exclusive_builds.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/toolchain.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/default_pre.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/win32/default_pre.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/resolve_config.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/exclusive_builds_post.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/default_post.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/precompile_header.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/warn_on.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/qt.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/resources_functions.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/resources.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/moc.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/win32/opengl.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/uic.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/qmake_use.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/file_copies.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/win32/windows.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/testcase_targets.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/exceptions.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/yacc.prf:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/lex.prf:
QR-Code.pro:
/usr/x86_64-w64-mingw32/lib/qt/mkspecs/features/build_pass.prf:
translations.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile QR-Code.pro

qmake_all: FORCE

make_first: release-make_first debug-make_first  FORCE
all: release-all debug-all  FORCE
clean: release-clean debug-clean  FORCE
distclean: release-distclean debug-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash

release-mocclean:
	$(MAKE) -f $(MAKEFILE).Release mocclean
debug-mocclean:
	$(MAKE) -f $(MAKEFILE).Debug mocclean
mocclean: release-mocclean debug-mocclean

release-mocables:
	$(MAKE) -f $(MAKEFILE).Release mocables
debug-mocables:
	$(MAKE) -f $(MAKEFILE).Debug mocables
mocables: release-mocables debug-mocables

check: first

benchmark: first
FORCE:

$(MAKEFILE).Release: Makefile
$(MAKEFILE).Debug: Makefile
